FROM node:18-bookworm as base
RUN apt-get update && apt-get install -y openssl
WORKDIR /app
COPY .yarn ./.yarn
COPY yarn.lock package.json .yarnrc.yml ./
RUN yarn workspaces focus --all --production

FROM node:18-bookworm-slim as prod

ARG REACT_APP_BILLING_STATUS
ENV REACT_APP_BILLING_STATUS=$REACT_APP_BILLING_STATUS

ARG REACT_APP_TRIAL_END_DATE
ENV REACT_APP_TRIAL_END_DATE=$REACT_APP_TRIAL_END_DATE

ARG REACT_APP_ZOOM_RATE
ENV REACT_APP_ZOOM_RATE=$REACT_APP_ZOOM_RATE

ARG REACT_APP_ZOOM_LINK
ENV REACT_APP_ZOOM_LINK=$REACT_APP_ZOOM_LINK

ARG REACT_APP_CHAT_USER_ID
ENV REACT_APP_CHAT_USER_ID=$REACT_APP_CHAT_USER_ID

ARG REACT_APP_CHAT_SECRET
ENV REACT_APP_CHAT_SECRET=$REACT_APP_CHAT_SECRET

ARG REACT_APP_COACH
ENV REACT_APP_COACH=$REACT_APP_COACH

ARG REACT_APP_COACH_FIRST_NAME
ENV REACT_APP_COACH_FIRST_NAME=$REACT_APP_COACH_FIRST_NAME

ARG REACT_APP_USER_FIRST_NAME
ENV REACT_APP_USER_FIRST_NAME=$REACT_APP_USER_FIRST_NAME

ARG REACT_APP_USER_EMAIL
ENV REACT_APP_USER_EMAIL=$REACT_APP_USER_EMAIL

RUN apt-get update && apt-get install tini && apt-get clean -y && rm -rf /var/lib/apt/lists/*

ARG USERNAME=actual
ARG USER_UID=1001
ARG USER_GID=$USER_UID
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME
RUN mkdir /data && chown -R ${USERNAME}:${USERNAME} /data

WORKDIR /app
ENV NODE_ENV production
COPY --from=base /app/node_modules /app/node_modules
COPY package.json app.js ./
COPY src ./src
COPY migrations ./migrations
ENTRYPOINT ["/usr/bin/tini","-g",  "--"]
EXPOSE 5006
CMD ["node", "app.js"]
